export default {
    SET_ANNOUCEMENT: 'SET_ANNOUCEMENT',
    SET_LOADED: 'SET_LOADED',

    ADD_ANNOUCEMENT: 'ADD_ANNOUCEMENT',
    REMOVE_ANNOUCEMENT: 'REMOVE_ANNOUCEMENT',
    EDIT_ANNOUCEMENT:'EDIT_ANNOUCEMENT',

    SET_TITLE_FAST: 'SET_TITLE_FAST'
}
